import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>FullStack Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div className="bg-gradient-to-r from-cyan-500 to-blue-500 text-white">
          <h1>Start Coding!</h1>
        </div>
      </section>
    </div>
  );
};

export default Home;
